// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAo9TwatO21hn1V5irnF0dQ47JP7OcWKo',
    appId: '1:897677978291:web:d5987a6b1210a0dc8cdec6',
    messagingSenderId: '897677978291',
    projectId: 'streaming-team-assistance',
    authDomain: 'streaming-team-assistance.firebaseapp.com',
    storageBucket: 'streaming-team-assistance.appspot.com',
    measurementId: 'G-HLP9SS7GSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL0VI8d6s57wfPOrcoAjK2_LzBcSqBKlo',
    appId: '1:897677978291:android:be111c0615c4d6308cdec6',
    messagingSenderId: '897677978291',
    projectId: 'streaming-team-assistance',
    storageBucket: 'streaming-team-assistance.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfBquPFJC2yqPpXOSH_9MVp5Jip8G3m4E',
    appId: '1:897677978291:ios:5fce7760c64662c58cdec6',
    messagingSenderId: '897677978291',
    projectId: 'streaming-team-assistance',
    storageBucket: 'streaming-team-assistance.appspot.com',
    iosClientId: '897677978291-vd1k8eelsq3rh9vq1jll0qfj3auahgsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamTeamAssistance',
  );
}
